baseurl = "https://imti.co"
relativeURLs = true
title = "IMTI"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
disqusShortname = ""
googleAnalytics = "UA-78786435-1"
preserveTaxonomyNames = true
hasCJKLanguage = true
publishDir = "docs"

[pagination]
  pagerSize = 30 #frontpage pagination

displayMath = [['$','$'], ['$$','$$'], ['\\[','\\]']]

[markup.goldmark.renderer]
unsafe= true

[outputs]
home = ["HTML", "RSS"]

[params]
  ISO8601 = "2006-01-02T15:04:05-07:00"

  header_image = "img/imti.jpg"
  SEOTitle = "| Craig Johnston"
  description = "I lead a talented team of software development and creative engineers, covering many industries looking to collect, analyze, move, buffer, queue, process and present data in significant ways. My expertise and that of my team revolve around microservices, artificial intelligence, algorithms, and machine learning."
  keyword = "Go, Kubernetes, Elasticsearch, Python, Docker, Big Data, Artificial Intelligence, Machine Learning"
  slogan = "Architecting, Developing, SRE, DevOps, AI/ML"

  image_404 = "img/404-bg.jpg"
  title_404 = "Nothing"

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "I lead a talented team of software development and creative engineers, covering many industries looking to collect, analyze, move, buffer, queue, process and present data in significant ways. My expertise and that of my team revolve around microservices, artificial intelligence, algorithms, and machine learning."
  sidebar_avatar = "/img/avatar-cj.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true
  featured_condition_size = 2

  # Baidu Analytics
  ba_track_id = ""

  # We need a proxy to access Disqus api in China
  disqus_proxy = ""
  disqus_site = ""

  [params.social]
  rss            = true
  email          = "cjimti@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  twitter       = "https://twitter.com/cjimti"
  linkedin       = "https://www.linkedin.com/in/cjimti/"
  stackoverflow  = "https://stackoverflow.com/users/265026/cjimti?tab=profile"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/cjimti"
  #wechat         = "link of wechat QR code image"
  #pinterest     = "full profile url in pinterest"

  [[params.bookmark_link]]
  title = "Kubefwd"
  href =  "https://kubefwd.com"
  [[params.bookmark_link]]
  title = "TXN2 OSS"
  href = "https://txn2.com"
  [[params.bookmark_link]]
  title =  "Author"
  href =  "https://www.amazon.com/Craig-Johnston/e/B001K80LWI/ref=ntt_dp_epwbk_0"
  [[params.bookmark_link]]
  title =  "Deasil Works"
  href =  "https://deasil.works/"

  [[params.github_link]]
  title = "txn2/kubefwd"
  href =  "https://github.com/txn2/kubefwd/"

  [[params.github_link]]
  title = "txn2/txeh"
  href =  "https://github.com/txn2/txeh/"

  [[params.github_link]]
  title = "txn2/mcp-data-platform"
  href =  "https://github.com/txn2/mcp-data-platform/"

  [[params.github_link]]
  title = "txn2/mcp-datahub"
  href =  "https://github.com/txn2/mcp-datahub/"

  [[params.github_link]]
  title = "txn2/mcp-trino"
  href =  "https://github.com/txn2/mcp-trino/"

  [[params.github_link]]
  title = "txn2/mcp-s3"
  href =  "https://github.com/txn2/mcp-s3/"

#  [[params.bookmark_link]]
#  title = "Hacker News"
#  href =  "https://news.ycombinator.com/"
#  [[params.bookmark_link]]
#  title = "Hacker News (cjimti)"
#  href =  "https://news.ycombinator.com/submitted?id=cjimti"

#  [[params.reddit_link]]
#  title = "user/imti_co"
#  href =  "https://www.reddit.com/user/imti_co/posts/"
#  [[params.reddit_link]]
#  title = "r/programming"
#  href =  "https://www.reddit.com/r/programming/"
#  [[params.reddit_link]]
#  title = "r/golang"
#  href =  "https://www.reddit.com/r/golang/"
#  [[params.reddit_link]]
#  title = "r/python"
#  href =  "https://www.reddit.com/r/python/"
#  [[params.reddit_link]]
#  title = "r/kubernetes"
#  href =  "https://www.reddit.com/r/kubernetes/"
#  [[params.reddit_link]]
#  title = "r/docker"
#  href =  "https://www.reddit.com/r/docker/"
#  [[params.reddit_link]]
#  title = "r/elasticsearch"
#  href =  "https://www.reddit.com/r/elasticsearch/"
#  [[params.reddit_link]]
#  title = "r/apachekafka"
#  href =  "https://www.reddit.com/r/apachekafka/"

#  [[params.docker_link]]
#  title = "n2proxy"
#  href =  "https://hub.docker.com/r/txn2/n2proxy/"
#  [[params.docker_link]]
#  title = "iotwifi"
#  href =  "https://hub.docker.com/r/cjimti/iotwifi/"
#  [[params.docker_link]]
#  title = "irsync"
#  href =  "https://hub.docker.com/r/cjimti/irsync/"
#  [[params.docker_link]]
#  title = "rxtx"
#  href =  "https://hub.docker.com/r/txn2/rxtx/"
#  [[params.docker_link]]
#  title = "rtbeat"
#  href =  "https://hub.docker.com/r/txn2/rtbeat/"
#  [[params.docker_link]]
#  title = "asws"
#  href =  "https://hub.docker.com/r/txn2/asws/"
#  [[params.docker_link]]
#  title = "txtoken"
#  href =  "https://hub.docker.com/r/txn2/txtoken/"
#  [[params.docker_link]]
#  title = "kubefwd"
#  href =  "https://hub.docker.com/r/txn2/kubefwd/"

#  [[params.awesome_link]]
#  title = "Kubernetes"
#  href = "https://github.com/ramitsurana/awesome-kubernetes"
#
#  [[params.awesome_link]]
#  title = "Cloud Native"
#  href = "https://github.com/rootsongjc/awesome-cloud-native"
#
#  [[params.awesome_link]]
#  title = "Raspberry Pi"
#  href = "https://github.com/thibmaek/awesome-raspberry-pi"
